name: Netlify CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          publish-dir: 'dist'
          production: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # NETLIFY_AUTH_TOKEN & NETLIFY_SITE_ID need to be set in repo secrets
